### ISSUE TITLE
WorkflowServerRails should be the repository of the workflow definition

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/workflow-server-rails#102]
Currently the workflow definition is held in a Dor::WorkflowObject in the repository.  This should be moved to the workflow service itself.

This would allow the workflow service to know what steps still need to be completed, and would relieve Argo/dor-indexer-app/robot-master of the responsibility of figuring out what work still needs to happen.

**Comment by justinlittman** [comment]
Done.
