### ISSUE TITLE
Versioning does not appear to be working as expected in -prod

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/workflow-server-rails#146]
While new content is moving through the system (though not always in ways that make it easy to track), we're seeing all versioned materials stacking up and not moving through common-accessioning. To demonstrate, let's look at a single object currently stuck in the workflow:

https://argo.stanford.edu/view/druid:dx943rw6966

When I look at the workflow database for this object, I see:
![Screenshot 2019-03-21 13 37 38](https://user-images.githubusercontent.com/796990/54783523-d29f7800-4bde-11e9-844e-ccfbd788cd65.png)

My understanding of this table is that:

1. version 2 is the active_version for the accessionWF
2. version 1 is no longer active for the accessionWF

This is reflected by the t/f indicators in the active_version column.

When I look in the workflow grid for this object, I see:

![Screenshot 2019-03-21 13 43 34](https://user-images.githubusercontent.com/796990/54783750-6e30e880-4bdf-11e9-88e9-60f5e7a8e7f8.png)

Which matches what is being shown in the database.

However, the object is not progressing through the workflow steps at all. When we tested this in -stage, it worked, but for some reason it is not working in -prod.

**Comment by jcoyne** [comment]
It's recorded in the WFS as 'queued', but possibly it hasn't been queued?

**Comment by jcoyne** [comment]
on each robot server I did this.
```
$ cd common-accessioning/current/log
$ grep dx943rw6966 dor_accessionWF_descriptive-metadata.log
$ zgrep -n dx943rw6966 dor_accessionWF_descriptive-metadata.log-20190321.gz
```

I see that it was processed on robots3-prod and robots5-prod

```
 INFO [2019-03-21 09:28:02] (24914)  :: druid:dx943rw6966 processing
 WARN [2019-03-21 09:28:02] (24914)  :: Item druid:dx943rw6966 is not queued, but has status of 'completed'. Will skip processing
```

then it sent a call to wfs:

```
I, [2019-03-20T11:30:15.811016 #2603]  INFO -- : [Attempt 1] put https://lyberservices-prod.stanford.edu/workflow//dor/objects/druid:dx943rw6966/workflows/accessionWF/descriptive-metadata
```

on the wfs the only thing I see is this:

 ```
$ grep objects/druid:dx943rw6966/workflows/accessionWF/descriptive-metadata /var/log/httpd/error_log
App 14605 output: [74e43cfa-0675-4166-9258-cf0510b0b278] Started PUT "/dor/objects/druid:dx943rw6966/workflows/accessionWF/descriptive-metadata?current-status=waiting" for 171.67.35.38 at 2019-03-21 09:28:01 -0700```
```

**Comment by jcoyne** [comment]
I think the bug is in dor-workflow-service:
```
 Dor::Config.workflow.client.get_workflow_status('dor', 'druid:dx943rw6966', 'accessionWF', 'descriptive-metadata') => 'completed'
```

**Comment by jcoyne** [comment]
The problem here was that the common-accessioning hadn't been refreshed in many weeks, so it was running an old version of dor-workflow-service which was unaware of the new workflow service.

**Comment by blalbrit** [comment]
Looking good in prod now. Okay to close?
