### ISSUE TITLE
Create a route that shows workflows for all repositories.

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/workflow-server-rails#156]
Currently any sdr repository workflows are not being indexed as they used to. This is because the old Java service ignored the repository parameter: https://github.com/sul-dlss/workflow-service/blob/26aeb8d8ee0e392f33948a29e17bfd0e8d61d472/src/edu/stanford/sulair/dlss/dor/resource/WorkflowResource.java#L187-L200

We should make a new route `/objects/{druid}/workflows` that shows workflows for all repositories.  Then we should make the old route redirect to this new one.  We must keep the old route working (a redirect is fine) because all the repository objects have dsLocation encoded in them and we don't want to update them all.

**Comment by jcoyne** [comment]
Before this is resolved, we should restore the redirect.  That will involve, updating the firewalls for services that call workflow-service, updating shared configs and updating dor-workflow-service so it can follow redirects.

**Comment by jcoyne** [comment]
This will require Argo and dor-indexing-app (at a minimum) to be upgraded to dor-services 7

**Comment by ndushay** [comment]
Is this still relevant?

**Comment by jcoyne** [comment]
No longer a concern now that Fedora 3 has been removed. Old routes removed in https://github.com/sul-dlss/workflow-server-rails/commit/1540a5be010764067ef209266b9724e39c31a0fc
