### ISSUE TITLE
Create a new event service.

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/workflow-server-rails#270]
This will take messages like these:

```
{
  object: 'druid:123',
  version: '3'
  name: 'workflow-step-complete'
  context: {
    duration: '30s'
    workflowName: 'accessionWF'
    workflowStep: 'technical-metadata'
    ...
  }
}

{
  object: 'druid:123',
  version: '3'
  name: 'registered'
  context: {
    who: 'peter'
    where: 'argo'
   data: {
     label: 'my object'
   }
  }
}

{
  object: 'druid:123',
  version: '3'
  name: 'preserved'
  context: {
    message: 'pushed into preservation core'
  }
}
```

The context can vary based on the name.  

This will allow us to have better visibility into how an object moves through the system.  We can write actors that are invoked when these messages are encountered, e.g. (workflow transition)

**Comment by justinlittman** [comment]
Is there an ADR for this?

**Comment by jcoyne** [comment]
we're working on it.

**Comment by mjgiarlo** [comment]
Planning to push up a whole slate of draft ADR PRs today.

**Comment by jcoyne** [comment]
Today we found that this endpoint would be particularly good for replacing `preservationAuditWF`, which is not a true workflow, but it used to surface preservation errors about an object.

**Comment by ndushay** [comment]
is this now done?

**Comment by jcoyne** [comment]
Yes, done in dor-services-app.
