### ISSUE TITLE
Update database sequence to be above the max inserted val

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/workflow-server-rails#28]
Something like this:

```
 ./bin/rails dbconsole -e production --include-password

select setval('workflow_steps_id_seq', select max(id) from workflow_steps);
```

This has already been done on `workflow-service-stage`. It will need to be done on `workflow-service-prod` immediately after the production data has been imported (#26). This is currently planned for early morning on Thursday, January 31st.

Blocked by #26

**Comment by mjgiarlo** [comment]
@jcoyne Can you clarify the intent of this issue and how I might verify that it's done?

**Comment by jcoyne** [comment]
This is part of the migration process.  You know it's done because when you do WorkflowStep.create, the id of the new step will be a number > 4000000
