### ISSUE TITLE
Add rails model level validation to ensure that we do not have duplicate rows for the same workflow/step/version

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/workflow-server-rails#282]
This will allow us to prevent new bad data from being added where we have duplicate rows for the same druid/workflow/step/version combination even if we are not yet able to add a database constraint (due to existing bad data) - see #40 for the database constraint work

This validation can be added now even with bad data and will help debug where the bad data is coming from.

**Comment by jcoyne** [comment]
Instead, we can add a unique constraint in the database?
