### ISSUE TITLE
Investigate why indexing is spamming the workflow server with requests for undefined workflows

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/workflow-server-rails#310]
From Rob Smith on Dec 20, 2019 in Slack #dlss-infrastructure channel.

The apache error_log on workflow-service-prod \var\log\httpd\error_log is constantly being written to with lines like:

```
App 20765 output: [d205e6f2-77e3-4562-943f-5fe78c394022] [2019-12-20 22:35:34.896] Started GET "/workflow_templates/googleScannedBookWF" for 171.67.35.78 at 2019-12-20 14:35:34 -0800
App 20765 output: [d205e6f2-77e3-4562-943f-5fe78c394022] [2019-12-20 22:35:34.896] Processing by WorkflowTemplatesController#show as JSON
App 20765 output: [d205e6f2-77e3-4562-943f-5fe78c394022] [2019-12-20 22:35:34.896]   Parameters: {"id"=>"googleScannedBookWF"}
App 20765 output: [d205e6f2-77e3-4562-943f-5fe78c394022] [2019-12-20 22:35:34.896] Completed 404 Not Found in 0ms (ActiveRecord: 0.0ms)
```

Looks like requests coming from dor-indexing-app-prod-b requesting possibly defunct and undefined googleScannedWF.

**Comment by peetucket** [comment]
i presume this is some auto re-indexing process that is indexing druids that have this workflow, and the indexing app is going to look for that workflow definition, and its no longer a valid workflow, so its throwing 404s

which all kinds of makes sense from a theoretical perspective, except for the "filling up the log" problem

**Comment by peetucket** [comment]
Note, indexing actually happens in `dor-services` gem here: https://github.com/sul-dlss/dor-services/blob/master/lib/dor/indexers/workflows_indexer.rb so that is the spot that likely makes the 404 calls out to `workflow-server-rails` (maybe needs to be shortcut by asking it to not make calls for unknown workflows?)

**Comment by jcoyne** [comment]
I will confirm that this is the indexer.  It needs the workflow templates so that it know which steps are expected. The fix would be to move the missing workflows into the workflow-service

**Comment by jcoyne** [comment]
We could add some exceptions to the indexing code so it skips over workflows we know are decommissioned or delete those steps from the workflow server.

**Comment by peetucket** [comment]
I like the exceptions idea rather than deleting the workflow entries.  Basically just enumerate all known deprecated workflows (would just be 3 or 4 probably) and then skip template look ups for those found in the list.  It also speeds up indexing by saving all those useless 404 calls to workflow-server-rails.

**Comment by ndushay** [comment]
is this now moot?

**Comment by peetucket** [comment]
probably
