### ISSUE TITLE
DELETE on /objects/{druid}/workflows always returns 204

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss/workflow-server-rails#351]
If an object has no workflows (i.e. WorkflowStep.where(druid: params[:druid]) is empty) a 204 (No Content) is returned.

If an object has workflows the delete (WorkflowStep.where(druid: params[:druid]).destroy_all) is performed and a 204 (No content) is returned

The first one makes sense, but I'm wondering if the second should be a 202 (Accepted) or a 200 with some basic response content?

Mostly just capturing what I'm seeing while working on the OPENAPI spec, feel free to close this if necessary.

**Comment by jcoyne** [comment]
Per https://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html#sec9.7
>  A successful response SHOULD be 200 (OK) if the response includes an entity describing the status, 202 (Accepted) if the action has not yet been enacted, or 204 (No Content) if the action has been enacted but the response does not include an entity.
