### ISSUE TITLE
replace accessionWF and versioningWF "completed_at" timestamps with "created_at" timestamps for druids with incorrect lifecycle timestamps

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/workflow-server-rails#421]
A bug introduced with https://github.com/sul-dlss/workflow-server-rails/pull/410 resulted in many workflow step timestamps being improperly overwritten for items that had a new version created between 2020-08-18, when the change was deployed, and 2020-09-18, when the bug was fixed. Specifically, when a new version of a druid was accessioned, the completed_at timestamps for all versions of an active workflow were reset to the completed_at timestamps of the current version.

This issue does not affect accessioning functionality, but does result in misleading data in Argo. On item show pages, items appear to have been accessioned multiple times in the same day because the lifecycle display shows the incorrect timestamps. It also throws off the "earliest accessioned" date facet, since items accessioned many years ago now appear to have been first accessioned in 2020. This also only affects items with more than one version. Items at version 1 have accurate information.

Restoring the original timestamps would be very labor intensive, and may not actually be possible for all items. As a compromise between precision and available resources, we've developed the following plan:

1. Find all druids affected
2. In the accessionWF, substitute the "created_at" timestamps into the "completed_at" field for earlier versions of these items

This should result in more accurate timestamps as the created_at dates in the accessionWF will reflect when the items started the accessionWF. It won't be 100% accurate, but will be far more accurate than what we have.

This search captures the vast majority of affected druids: https://argo.stanford.edu/catalog?utf8=%E2%9C%93&all=true&f[accessioned_latest_dttsi][]=[2020-08-18T12%3A00%3A00.000Z+TO+2020-09-18T23%3A59%3A59.000Z]&commit=submit

A smaller number of affected druids are not in that search because they were accessioned both while the bug was active (causing the timestamps to be overwritten) and after it was fixed (so they don't appear in the date-range limited search). I'm working on how to track those down.

**Comment by andrewjbtw** [comment]
Accidentally hit enter while typing title. Real issue forthcoming.

**Comment by andrewjbtw** [comment]
Amending this to add the versioningWF as well, since the "Opened" milestone is part of that workflow. We are using the created_at dates there as well because they were also overwritten for some versions.

**Comment by jcoyne** [comment]
Running https://github.com/sul-dlss/workflow-server-rails/compare/fix-timestamps#diff-c6460ab4f2a835b5032becc740b9789b to fix.
