### ISSUE TITLE
setting an errored step to completed via the workflow rake task doesn't clear the error message in the workflow database

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/workflow-server-rails#422]
**Describe the bug**

Occasionally, an errored workflow step needs to be set to completed manually via the rake task on the workflow server.

Example:

For https://argo.stanford.edu/view/druid:bg032kt2854 the update-catalog step needed to be set to completed because a re-run of the step would fail, and the step had already been completed in the background. (This is related to https://github.com/sul-dlss/preservation_catalog/issues/1634 where prescat and pres-robots can act on the same druid.)

In the error state, the Argo display looked like this:
<img width="400" alt="Screen Shot 2020-10-02 at 2 14 25 PM" src="https://user-images.githubusercontent.com/8975583/94972376-fa52ea00-04bd-11eb-9a3e-0886e94d6884.png">
 
After setting the step to completed with

```ruby
RAILS_ENV=production bundler exec rake workflow:step[druid:bg032kt2854,preservationIngestWF,update-catalog,4,completed]
```

the Argo display looks like this

<img width="400" alt="Screen Shot 2020-10-02 at 2 43 51 PM" src="https://user-images.githubusercontent.com/8975583/94972430-1a82a900-04be-11eb-9b81-6034dc81866a.png">

In the second screenshot you can see that the object has been accessioned and all workflows are completed, but the error message is still present in Argo and in the workflow database.

**User impact**

It's confusing to see a druid where everything looks successful but an error message is still showing.

**Expected behavior**

Setting a step to completed should also clear any error message for that step.

**Comment by jcoyne** [comment]
It works if you use the API (in Argo):

```
workflow_client = WorkflowClientFactory.build
 workflow_client.update_status(druid: druid, workflow: 'accessionWF', process: 'content-metadata', status: 'completed')
```
