### ISSUE TITLE
remove gisDiscoveryWF as it is no longer in use

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/workflow-server-rails#466]
of course, it is important to be concerned with objects that may have it partially done and all the other caveats re: removing a workflow.

**Comment by andrewjbtw** [comment]
I don't know if it's going to happen here but in the past the workflow grid/indexing has complained when a deprecated workflow was removed from its list. It's one reason deprecated workflows are still on the grid.

**Comment by mjgiarlo** [comment]
@andrewjbtw I'm looking into this in stage right now to suss out what we need to do to avoid this.
