### ISSUE TITLE
Config for robot master

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/workflow-server-rails#53]
in `sul-lyberservices-test:/home/lyberadmin/robot-master/current/config/environments/test.rb`

```ruby
url 'http://workflow-stage.stanford.edu/workflow'
```

This should point at the proxy (or the new server)

This is not in shared_configs

**Comment by jcoyne** [comment]
Changed to `url 'http://lyberservices-test.stanford.edu/workflow/'` and redeployed robot-master stage

**Comment by jcoyne** [comment]
Reverted this change because of #55

**Comment by mjgiarlo** [comment]
#55 is now closed so I am closing this issue once again.
