### ISSUE TITLE
Remove skipped steps from the gisAssemblyWF

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/workflow-server-rails#567]
https://github.com/sul-dlss/workflow-server-rails/blob/main/config/workflows/gisAssemblyWF.xml#L78-L85

**Comment by jcoyne** [comment]
Should this have included approve-metadata too?

**Comment by peetucket** [comment]
Personally I'm not familiar enough with this workflow to know if those steps are still useful.  Though with this workflow definition, I think they would always be skipped automatically, so it's unclear as to their utility.
