### ISSUE TITLE
Add close item check step to beginning of accession WF

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/workflow-server-rails#738]
This step should Honeybadger alert if the item is open. (In the future, this will be changed to raising.)

One option would be to change the existing start-accessioning step so that it is handled by a robot rather than automatically completed.

**Comment by jcoyne** [comment]
I believe this is already done in DSA by ObjectsController#accession

**Comment by justinlittman** [comment]
ObjectsController#accession provides the ability to change version attributes (e.g., description) when closing. I believe this functionality is available to users in Argo, so removing it from the accessioning endpoint has rippling effects.

That being said, I'd like to see versioning in ObjectsController#accession so I will add it as a separate task to be considered later.

**Comment by lwrubel** [comment]
Needs https://github.com/sul-dlss/dor-services-app/issues/4779.

**Comment by andrewjbtw** [comment]
> I believe this functionality is available to users in Argo, so removing it from the accessioning endpoint has rippling effects.

Yes, this is in the close modal on show pages and gives people a chance to update their version description in case they did something different than originally intended.

**Comment by aaron-collier** [comment]
I picked this up but I'm not entirely sure where this check should go (or how it fits in workflow server). I'm happy to pick it back up with some pairing however (understanding we're at the end of most folks day).

**Comment by mjgiarlo** [comment]
Closed by above PRs.
