### ISSUE TITLE
Add step to beginning of all assembly workflows to check that the item is open

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/workflow-server-rails#750]
And Honeybadger alert if it is not.

The assembly workflows are:

- assemblyWF
- ~~etdSubmitWF~~ (see [comments below](https://github.com/sul-dlss/workflow-server-rails/issues/750#issuecomment-2043513018))
- gisAssemblyWF
- wasCrawlPreassemblyWF
- wasSeedPreassemblyWF

**Comment by jcoyne** [comment]
Why do we need this?

**Comment by justinlittman** [comment]
Assembly workflows change cocina and files. Hence, they must be performed on an open item. However, there is nothing about starting a workflow that enforces a particular versioning state. This guarantees that the item will be in the correct versioning state to avoid problems further in the workflow.

**Comment by jcoyne** [comment]
@justinlittman are you certain we need this for etdSubmitWF? That workflow is all manual (no robots).

**Comment by justinlittman** [comment]
Part of etdSubmitWF is completed by https://github.com/sul-dlss/hydra_etd/blob/main/app/jobs/other_metadata_job.rb, which involves updating the cocina.

I'm unclear whether the item should be open through that entire workflow or just opened for the single step. @andrewjbtw ?

**Comment by jcoyne** [comment]
@justinlittman Yes, but those aren't "robots", they are external to the whole workflow/robots system.

**Comment by justinlittman** [comment]
Why is it guaranteed to be open for an etd?

**Comment by jcoyne** [comment]
@justinlittman because all ETDs are a one time deposit.  There is only ever one instance of the submit workflow ever created and it's always done on a newly created object.

**Comment by justinlittman** [comment]
OK, so I agree with omitting edtSubmitWF.

**Comment by jcoyne** [comment]
See also https://github.com/sul-dlss/hydra_etd/issues/350

**Comment by andrewjbtw** [comment]
Yes, ETDs currently have "registered" status throughout the edtSubmitWF. As far as I know, any remediation for ETDs will go through accessionWF and possibly assemblyWF but never etdSubmitWF again.
