### ISSUE TITLE
Add fetch_files step definition to ocrWF

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/workflow-server-rails#767]
See https://github.com/sul-dlss/common-accessioning/pull/1210   -- this adds a new robot, and we need the new definition in ocrWF before `ocr-create`: https://github.com/sul-dlss/workflow-server-rails/blob/main/config/workflows/ocrWF.xml

**Comment by jmartin-sul** [comment]
this about wiring up the work in https://github.com/sul-dlss/common-accessioning/pull/1210
