### ISSUE TITLE
Add messaging

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/workflow-server-rails#77]
https://github.com/sul-dlss/workflow-service/blob/26aeb8d8ee0e392f33948a29e17bfd0e8d61d472/integration-tests-module/test-integration/edu/stanford/sulair/dlss/dor/service/FedoraActiveMqTests.java#L59-L74

**Comment by mjgiarlo** [comment]
Message format: https://github.com/sul-dlss/workflow-service/blob/master/src/edu/stanford/sulair/dlss/dor/service/JmsMessagingService.java#L61-L74

Each create/update triggers a message being sent: https://github.com/sul-dlss/workflow-service/blob/26aeb8d8ee0e392f33948a29e17bfd0e8d61d472/src/edu/stanford/sulair/dlss/dor/service/WorkflowServiceImpl.java#L40-L57

And you can see here that the only specific info coming over is the druid: https://github.com/sul-dlss/workflow-service/blob/26aeb8d8ee0e392f33948a29e17bfd0e8d61d472/src/edu/stanford/sulair/dlss/dor/service/WorkflowServiceImpl.java#L98-L129

**Comment by mjgiarlo** [comment]
Send all messages to `dor.messaging` broker: https://github.com/sul-dlss/workflow-service/pull/8

**Comment by mjgiarlo** [comment]
Configuration: 

```
# Destination of JMS messages
dor.jms.broker.url=failover:(tcp://sulmq-prod-a.stanford.edu:61616,tcp://sulmq-prod-b.stanford.edu:61616)

# The fedora host is sent inside the JMS message as the `entry.author.uri` field
dor.fedora.host.uri=https://dor-test.stanford.edu
```
