### ISSUE TITLE
Use shared_configs to manage secrets

### ISSUE THREAD

**Issue by mjgiarlo** [sul-dlss/workflow-server-rails#8]
When we merged https://github.com/sul-dlss-labs/workflow-server-rails/pull/5, we committed a secret (though not one we care much about) to a public repository. Once we pull in Capistrano and shared_configs, we should regenerate the Honeybadger API key and discontinue storing this config file in the workflow-server-rails repository, preferring instead to use shared_configs for this.

**Comment by jcoyne** [comment]
Done!

**Comment by mjgiarlo** [comment]
Fixed in https://github.com/sul-dlss/workflow-server-rails/pull/13
